apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsearch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsearch
  template:
    metadata:
      labels:
        app: wordsearch
    spec:
      containers:
      - name: wordsearch
        image: wordsearch:latest
        ports:
        - containerPort: 8085
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: wordsearch-service
spec:
  type: LoadBalancer
  selector:
    app: wordsearch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085